site_name: simple-pip
repo_url: 'https://github.com/frogweezer/simple-pip'
repo_name: frogweezer/simple-pip
theme:
  name: null
  custom_dir: mkdocs-material/material
  logo: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Source code: source.md
  - How to use simple-pip with other apps: other-apps.md
